# Generated by Django 6.1.1 on 2026-09-14 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="Identificativo univoco per l'URL, es. fit-club-barletta", unique=True)),
                ('citta', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='palestre/loghi/')),
            ],
        ),
        migrations.CreateModel(
            name='CorsoOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('video_url', models.URLField(help_text='Link del video (es. YouTube non in elenco o Vimeo)')),
                ('prezzo', models.DecimalField(decimal_places=2, default=0.0, help_text='0.00 se il corso è gratuito', max_digits=6)),
                ('is_gratuito', models.BooleanField(default=False)),
                ('palestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corsi', to='gym.palestra')),
            ],
        ),
        migrations.CreateModel(
            name='Attrezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descrizione', models.TextField()),
                ('muscoli_coinvolti', models.CharField(help_text='Es. Petto, Tricipiti, Spalle', max_length=255)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='attrezzi/')),
                ('palestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrezzi', to='gym.palestra')),
            ],
        ),
    ]
