# Generated by Django 6.1.1 on 2026-09-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corsoonline',
            name='video_url',
        ),
        migrations.AddField(
            model_name='corsoonline',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='corsi_video/'),
        ),
    ]
