# Generated by Django 6.1.1 on 2026-09-14 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_remove_corsoonline_video_url_corsoonline_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAttrezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='attrezzo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.categoriaattrezzo'),
        ),
    ]
