# Generated by Django 6.1.1 on 2026-09-15 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_categoriaattrezzo_immagine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abbonamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_piano', models.CharField(max_length=100)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('durata', models.CharField(max_length=50)),
                ('descrizione', models.TextField()),
                ('caratteristiche', models.TextField(help_text='Inserisci le caratteristiche separate da virgola o punto')),
                ('palestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abbonamenti', to='gym.palestra')),
            ],
        ),
    ]
