# Generated by Django 6.1.1 on 2026-09-15 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_abbonamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrarioApertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.CharField(choices=[('Lunedì', 'Lunedì'), ('Martedì', 'Martedì'), ('Mercoledì', 'Mercoledì'), ('Giovedì', 'Giovedì'), ('Venerdì', 'Venerdì'), ('Sabato', 'Sabato'), ('Domenica', 'Domenica')], max_length=20)),
                ('orario_apertura', models.CharField(max_length=50)),
                ('chiuso', models.BooleanField(default=False)),
                ('palestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orari', to='gym.palestra')),
            ],
        ),
    ]
