# Generated by Django 6.1.1 on 2026-09-16 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_orarioapertura'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('specializzazione', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='trainers/')),
                ('giorni_disponibili', models.CharField(max_length=100)),
                ('palestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='gym.palestra')),
            ],
        ),
    ]
