# Generated by Django 6.1.1 on 2026-09-16 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_personaltrainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrenotazioneContatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_utente', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('messaggio', models.TextField()),
                ('data_richiesta', models.DateTimeField(auto_now_add=True)),
                ('palestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='gym.palestra')),
            ],
        ),
    ]
