# Generated by Django 6.1.1 on 2026-09-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_coursebooking_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='rest_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tempo di Recupero'),
        ),
    ]
