# Generated by Django 6.1.1 on 2026-09-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_workoutexercise_rest_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Video Dimostrativo'),
        ),
    ]
