# Generated by Django 6.1.1 on 2026-09-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0014_workoutexercise_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='video_url',
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='exercises_videos/', verbose_name='File Video Esercizio'),
        ),
    ]
