# Generated by Django 6.1.1 on 2026-09-19 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0016_exerciselog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo Piano Alimentare')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Linee Guida / Consigli Nutrizionali')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='diet_pdfs/', verbose_name='File PDF Dieta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
