# Generated by Django 6.1.1 on 2026-09-19 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0021_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='progress_photos/', verbose_name='Foto Progresso')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Didascalia o Note')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data Caricamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
