# Generated by Django 6.1.1 on 2026-09-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0023_referralprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titolo Lezione')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('video_url', models.URLField(verbose_name='URL Video (es. YouTube o Vimeo)')),
                ('duration', models.CharField(max_length=20, verbose_name='Durata (es. 45 min)')),
                ('instructor', models.CharField(max_length=100, verbose_name='Istruttore')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
