# Generated by Django 6.1.1 on 2026-09-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0024_videolesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='videolesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='File Video (MP4)'),
        ),
    ]
