# Generated by Django 6.1.1 on 2026-09-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0025_remove_videolesson_video_url_videolesson_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Letta'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titolo'),
        ),
    ]
