# Generated by Django 6.1.1 on 2026-09-19 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0026_alter_notification_is_read_alter_notification_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsWhatsappLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numero di Telefono')),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS')], default='WHATSAPP', max_length=10, verbose_name='Canale')),
                ('message_type', models.CharField(max_length=50, verbose_name='Tipo Avviso (es. Scadenza, Promemoria)')),
                ('message_body', models.TextField(verbose_name='Testo Messaggio')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Inviato', max_length=20, verbose_name='Stato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_whatsapp_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
