# Generated by Django 6.1.1 on 2026-09-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0028_memberpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymLiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy_percentage', models.IntegerField(default=45, verbose_name='Affluenza Attuale (%)')),
                ('status_label', models.CharField(default='Tranquillo & Ottimale', max_length=50, verbose_name='Stato Affluenza')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
