# Generated by Django 6.1.1 on 2026-09-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0029_gymlivestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Attrezzo')),
                ('category', models.CharField(max_length=50, verbose_name='Categoria (es. Cardio, Isotonico, Sala Pesi)')),
                ('status', models.CharField(choices=[('OTTIMO', '🟢 Operativo / Perfetto'), ('MANUTENZIONE', '🟠 In Manutenzione Programmata'), ('GUASTO', '🔴 Fuori Uso / Segnalato')], default='OTTIMO', max_length=20, verbose_name='Stato Attrezzo')),
                ('last_check_date', models.DateField(auto_now_add=True, verbose_name='Ultimo Controllo')),
            ],
        ),
    ]
