# Generated by Django 6.1.1 on 2026-09-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0030_gymequipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpass',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
