# Generated by Django 6.1.1 on 2026-09-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0034_userprofile_age_userprofile_height_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('schedule_time', models.DateTimeField()),
                ('max_capacity', models.IntegerField(default=15)),
                ('current_booked', models.IntegerField(default=0)),
            ],
        ),
    ]
