# Generated by Django 6.1.1 on 2026-09-22 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0035_gymcourse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebooking',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.corsoonline'),
        ),
        migrations.AlterField(
            model_name='coursebooking',
            name='status',
            field=models.CharField(default='Confermato', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursebooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='coursebooking',
            unique_together={('user', 'course')},
        ),
    ]
