# Generated by Django 6.1.1 on 2026-09-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0036_alter_coursebooking_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corsoonline',
            name='descrizione',
        ),
        migrations.RemoveField(
            model_name='corsoonline',
            name='is_gratuito',
        ),
        migrations.RemoveField(
            model_name='corsoonline',
            name='palestra',
        ),
        migrations.RemoveField(
            model_name='corsoonline',
            name='prezzo',
        ),
        migrations.RemoveField(
            model_name='corsoonline',
            name='titolo',
        ),
        migrations.RemoveField(
            model_name='corsoonline',
            name='video_file',
        ),
        migrations.AddField(
            model_name='corsoonline',
            name='current_booked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corsoonline',
            name='max_capacity',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='corsoonline',
            name='title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
