# Generated by Django 6.1.1 on 2026-09-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0037_remove_corsoonline_descrizione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palestra',
            name='descrizione_breve',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='palestra',
            name='immagine_copertina',
            field=models.ImageField(blank=True, null=True, upload_to='palestre/copertine/'),
        ),
    ]
