# Generated by Django 6.1.1 on 2026-09-22 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0039_recensione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotOrario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno_settimana', models.CharField(choices=[('Lunedi', 'Lunedì'), ('Martedi', 'Martedì'), ('Mercoledi', 'Mercoledì'), ('Giovedi', 'Giovedì'), ('Venerdi', 'Venerdì'), ('Sabato', 'Sabato'), ('Domenica', 'Domenica')], max_length=20)),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('posti_disponibili', models.PositiveIntegerField(default=20)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_orari', to='gym.corsoonline')),
            ],
        ),
        migrations.CreateModel(
            name='PrenotazioneCorso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prenotazione', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='gym.slotorario')),
            ],
        ),
    ]
